//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfManager.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class PdfFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PdfFile()
        {
            this.Tags = new HashSet<Tag>();
            this.CreateTime = DateTime.Now;
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "标题不能为空")]
        public string Tittle { get; set; }
        public DateTime CreateTime { get; set; }
        [Required(ErrorMessage = "文件名不能为空")]
        public string FileName { get; set; }
        public int? Year { get; set; }
        public long? FileId { get; set; }
        public string Other1 { get; set; }
        public string Other2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
